In [1]:
import pandas as pd
import numpy as np

## Duplicate Product IDs

In [ ]:
file_loc_dict = {}

with open('env.txt','r') as f:
  f_reader = f.readlines()

for x in f_reader:
  key = x.split("=")[0]
  val = x.split("=")[1].split('\n')[0]
  file_loc_dict[key] = val

In [3]:
# loc = "D:\github_windows\DE_CS_202309\Project"
# file = loc+"\\"+"Final.xlsx"

loc = file_loc_dict['data_iss_loc']
file = file_loc_dict['data_iss_file']

In [4]:
df = pd.read_excel(file)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Total_Sales,Price_After_Disc,Unit_Cost,Order_Type
0,1,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,523.92,261.96,130.98,Order
1,1,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,0.00,0,0.0,41.9136,0.00,0.00,0.00,Returns
2,1,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,0.00,0,0.0,41.9136,0.00,0.00,0.00,Returns
3,2,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,2195.82,731.94,243.98,Order
4,2,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",0.00,0,0.0,219.5820,0.00,0.00,0.00,Returns

In [5]:
df_prod = df[['Product ID','Category','Sub-Category','Product Name']]
df_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21680 entries, 0 to 21679
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    21680 non-null  object
 1   Category      21680 non-null  object
 2   Sub-Category  21680 non-null  object
 3   Product Name  21680 non-null  object
dtypes: object(4)
memory usage: 677.6+ KB

In [6]:
df_prod = df_prod.drop_duplicates()
df_prod.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1890 entries, 0 to 21550
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    1890 non-null   object
 1   Category      1890 non-null   object
 2   Sub-Category  1890 non-null   object
 3   Product Name  1890 non-null   object
dtypes: object(4)
memory usage: 73.8+ KB

In [7]:
df_prod.head()

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
3,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
6,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
9,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
10,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System

In [9]:
np.count_nonzero(df_prod['Product Name'].unique())

1838

In [21]:
df_prod[df_prod["Product ID"].duplicated()]

,Product ID,Category,Sub-Category,Product Name
289,FUR-CH-10001146,Furniture,Chairs,"Global Task Chair, Black"
2949,FUR-FU-10004091,Furniture,Furnishings,"Eldon 200 Class Desk Accessories, Black"
4689,FUR-FU-10001473,Furniture,Furnishings,"Eldon Executive Woodline II Desk Accessories, ..."
5202,FUR-BO-10002213,Furniture,Bookcases,"Sauder Forest Hills Library, Woodland Oak Finish"
8198,FUR-FU-10004017,Furniture,Furnishings,"Executive Impressions 13"" Chairman Wall Clock"

## Zero Sales

In [10]:
df_ret = df[df["Sales"] == 0]
df_ret.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10613 entries, 1 to 21675
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            10613 non-null  int64
 1   Order ID          10613 non-null  object
 2   Order Date        10613 non-null  object
 3   Ship Date         10613 non-null  datetime64[ns]
 4   Ship Mode         10613 non-null  object
 5   Customer ID       10613 non-null  object
 6   Customer Name     10613 non-null  object
 7   Segment           10613 non-null  object
 8   Country           10613 non-null  object
 9   City              10613 non-null  object
 10  State             10613 non-null  object
 11  Postal Code       10613 non-null  int64
 12  Region            10613 non-null  object
 13  Product ID        10613 non-null  object
 14  Category          10613 non-null  object
 15  Sub-Category      10613 non-null  object
 16  Product Name      10613 non-null  object
 17  Sales             10613 non-null  float64
 18  Quantity          10613 non-null  int64
 19  Discount          10613 non-null  float64
 20  Profit            10613 non-null  float64
 21  Total_Sales       10613 non-null  float64
 22  Price_After_Disc  10613 non-null  float64
 23  Unit_Cost         10613 non-null  float64
 24  Order_Type        10613 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(3), object(15)
memory usage: 2.1+ MB

In [11]:
df_ret.drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Total_Sales,Price_After_Disc,Unit_Cost,Order_Type
1,1,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,0.0,0,0.0,41.9136,0.0,0.0,0.0,Returns
4,2,CA-2021-152156,2021-11-09 00:00:00,2021-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",0.0,0,0.0,219.5820,0.0,0.0,0.0,Returns
7,3,CA-2021-138688,2021-06-13 00:00:00,2021-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,0.0,0,0.0,6.8714,0.0,0.0,0.0,Returns
12,6,CA-2019-115812,2019-06-09 00:00:00,2019-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,0.0,0,0.0,14.1694,0.0,0.0,0.0,Returns
14,7,CA-2019-115812,2019-06-09 00:00:00,2019-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Art,Newell 322,0.0,0,0.0,1.9656,0.0,0.0,0.0,Returns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21665,9986,CA-2020-100251,2020-05-17 00:00:00,2020-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,0.0,0,0.0,16.1240,0.0,0.0,0.0,Returns
21667,9987,CA-2021-125794,2021-09-30 00:00:00,2021-10-04,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,0.0,0,0.0,15.2208,0.0,0.0,0.0,Returns
21669,9988,CA-2022-163629,2022-11-18 00:00:00,2022-11-22,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,0.0,0,0.0,28.7964,0.0,0.0,0.0,Returns
21672,9989,CA-2022-163629,2022-11-18 00:00:00,2022-11-22,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,Phones,Panasonic KX - TS880B Telephone,0.0,0,0.0,55.6470,0.0,0.0,0.0,Returns
21675,9990,CA-2019-110422,2019-01-22 00:00:00,2019-01-24,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furnishings,Ultra Door Pull Handle,0.0,0,0.2,4.1028,0.0,0.0,0.0,Returns

In [12]:
df_ret['Order ID'].value_counts()

Order ID
CA-2021-165330    22
CA-2020-131338    20
CA-2021-145177    18
CA-2020-104346    18
CA-2022-161956    16
                  ..
CA-2022-122112     1
CA-2021-127649     1
CA-2020-143602     1
CA-2019-134061     1
CA-2019-110422     1
Name: count, Length: 3378, dtype: int64

## High Discount

In [13]:
df[(df["Discount"] > .70) & (df['Quantity']>0)].drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Total_Sales,Price_After_Disc,Unit_Cost,Order_Type
31,15,US-2020-118983,2020-11-22 00:00:00,2020-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580,344.050,13.7620,2.7524,Order
33,16,US-2020-118983,2020-11-22 00:00:00,2020-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.8160,7.632,0.5088,0.1696,Order
219,102,CA-2021-158568,2021-08-30 00:00:00,2021-09-03,Standard Class,RB-19465,Rick Bensley,Home Office,United States,Chicago,...,Binders,Avery Hidden Tab Dividers for Binding Systems,1.788,3,0.8,-3.0396,5.364,0.3576,0.1192,Order
383,170,CA-2019-139892,2019-09-08 00:00:00,2019-09-12,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,...,Appliances,Kensington 7 Outlet MasterPiece Power Center,177.980,5,0.8,-453.8490,889.900,35.5960,7.1192,Order
392,175,US-2019-100853,2019-09-14 00:00:00,2019-09-19,Standard Class,JB-15400,Jennifer Braxton,Corporate,United States,Chicago,...,Appliances,Kensington 7 Outlet MasterPiece HOMEOFFICE Pow...,52.448,2,0.8,-131.1200,104.896,10.4896,5.2448,Order
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21247,9795,CA-2019-127166,2019-05-21 00:00:00,2019-05-23,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,...,Binders,Ibico Plastic Spiral Binding Combs,18.240,3,0.8,-31.0080,54.720,3.6480,1.2160,Order
21250,9796,CA-2021-125920,2021-05-22 00:00:00,2021-05-29,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798,3,0.8,-5.8869,11.394,0.7596,0.2532,Order
21291,9809,CA-2022-145093,2022-07-22 00:00:00,2022-07-27,Standard Class,PT-19090,Pete Takahito,Consumer,United States,Chicago,...,Binders,"Wilson Jones 1"" Hanging DublLock Ring Binders",2.112,2,0.8,-3.3792,4.224,0.4224,0.2112,Order
21366,9836,CA-2021-126627,2021-10-11 00:00:00,2021-10-13,First Class,WB-21850,William Brown,Consumer,United States,La Porte,...,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",16.392,2,0.8,-26.2272,32.784,3.2784,1.6392,Order
21517,9921,CA-2021-149272,2021-03-16 00:00:00,2021-03-20,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.386,7,0.8,-35.8176,156.702,4.4772,0.6396,Order

## Date Issue

In [14]:
df["Order Date"] = df["Order Date"].astype('string')

In [15]:
np.count_nonzero(df[(df["Order Date"].str.contains("/"))]["Row ID"].unique())

27