In [4]:
import pandas as pd
import numpy as np

In [5]:
loc = "D:\github_windows\DE_CS_202309\Project"
file = loc+"\\"+"Final.xlsx"

## Duplicate Product IDs

In [6]:
loc = "D:\github_windows\DE_CS_202309\Project"
file = loc+"\\"+"Final.xlsx"

In [7]:
df = pd.read_excel(file)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Total Sales,Disc %,After Disc,Item Cost,Order Type
0,7981,CA-2019-103800,2019-01-04 00:00:00,2019-01-08,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,32.896,0.2,13.1584,0.8,Order
1,7981,CA-2019-103800,2019-01-04 00:00:00,2019-01-08,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",0.000,0,0.2,5.5512,0.000,0.2,0.0000,0.0,Returns
2,740,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Avery 508,11.784,3,0.2,4.2717,35.352,0.2,9.4272,0.8,Order
3,741,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,818.208,0.2,218.1888,0.8,Order
4,742,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,7.080,0.8,0.7080,0.2,Order

In [8]:
df_prod = df[['Product ID','Category','Sub-Category','Product Name']]
df_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21446 entries, 0 to 21445
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    21446 non-null  object
 1   Category      21446 non-null  object
 2   Sub-Category  21446 non-null  object
 3   Product Name  21446 non-null  object
dtypes: object(4)
memory usage: 670.3+ KB

In [9]:
df_prod = df_prod.drop_duplicates()
df_prod.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1886 entries, 0 to 20932
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    1886 non-null   object
 1   Category      1886 non-null   object
 2   Sub-Category  1886 non-null   object
 3   Product Name  1886 non-null   object
dtypes: object(4)
memory usage: 73.7+ KB

In [10]:
df_prod.head()

,Product ID,Category,Sub-Category,Product Name
0,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form..."
2,OFF-LA-10003223,Office Supplies,Labels,Avery 508
3,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving
4,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs
8,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...

In [11]:
np.count_nonzero(df_prod['Product ID'].unique())

1881

In [12]:
np.count_nonzero(df_prod['Product Name'].unique())

1834

## Zero Sales

In [13]:
df_ret = df[df["Sales"] == 0]
df_ret.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10613 entries, 1 to 21427
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10613 non-null  int64
 1   Order ID       10613 non-null  object
 2   Order Date     10613 non-null  object
 3   Ship Date      10613 non-null  datetime64[ns]
 4   Ship Mode      10613 non-null  object
 5   Customer ID    10613 non-null  object
 6   Customer Name  10613 non-null  object
 7   Segment        10613 non-null  object
 8   Country        10613 non-null  object
 9   City           10613 non-null  object
 10  State          10613 non-null  object
 11  Postal Code    10613 non-null  int64
 12  Region         10613 non-null  object
 13  Product ID     10613 non-null  object
 14  Category       10613 non-null  object
 15  Sub-Category   10613 non-null  object
 16  Product Name   10613 non-null  object
 17  Sales          10613 non-null  float64
 18  Quantity       10613 non-null  int64
 19  Discount       10613 non-null  float64
 20  Profit         10613 non-null  float64
 21  Total Sales    10613 non-null  float64
 22  Disc  %        10613 non-null  float64
 23  After Disc     10613 non-null  float64
 24  Item Cost      10613 non-null  float64
 25  Order Type     10613 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(3), object(15)
memory usage: 2.2+ MB

In [14]:
df_ret.drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Total Sales,Disc %,After Disc,Item Cost,Order Type
1,7981,CA-2019-103800,2019-01-04 00:00:00,2019-01-08,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",0.0,0,0.2,5.5512,0.0,0.2,0.0,0.0,Returns
5,740,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Avery 508,0.0,0,0.2,4.2717,0.0,0.2,0.0,0.0,Returns
6,741,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,SAFCO Boltless Steel Shelving,0.0,0,0.2,-64.7748,0.0,0.2,0.0,0.0,Returns
7,742,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,GBC Standard Plastic Binding Systems Combs,0.0,0,0.8,-5.4870,0.0,0.8,0.0,0.0,Returns
9,1760,CA-2019-141817,2019-01-06 00:00:00,2019-01-13,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,0.0,0,0.2,4.8840,0.0,0.2,0.0,0.0,Returns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21415,2880,CA-2021-152072,1/15/2021,2021-01-19,Standard Class,Dp-13240,Dean percer,Home Office,United States,Westfield,...,LogitechÂ Gaming G510s - Keyboard,0.0,0,0.0,91.7892,0.0,0.0,0.0,0.0,Returns
21416,2879,CA-2021-152072,1/15/2021,2021-01-19,Standard Class,Dp-13240,Dean percer,Home Office,United States,Westfield,...,American Pencil,0.0,0,0.0,1.3514,0.0,0.0,0.0,0.0,Returns
21417,3744,CA-2021-137848,1/15/2021,2021-01-21,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,"Square Ring Data Binders, Rigid 75 Pt. Covers,...",0.0,0,0.2,17.3376,0.0,0.2,0.0,0.0,Returns
21418,3742,CA-2021-137848,1/15/2021,2021-01-21,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,"#10 Gummed Flap White Envelopes, 100/Box",0.0,0,0.0,7.5992,0.0,0.0,0.0,0.0,Returns
21419,3743,CA-2021-137848,1/15/2021,2021-01-21,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,Xerox 1959,0.0,0,0.0,28.8576,0.0,0.0,0.0,0.0,Returns

In [15]:
df_ret['Order ID'].value_counts()

Order ID
CA-2021-165330    22
CA-2020-131338    20
CA-2020-104346    18
CA-2021-145177    18
CA-2022-161956    16
                  ..
CA-2021-155439     1
CA-2021-149370     1
CA-2021-149797     1
CA-2021-160479     1
CA-2019-103800     1
Name: count, Length: 3378, dtype: int64

## High Discount

In [16]:
df[(df["Discount"] > .70) & (df['Quantity']>0)].drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Total Sales,Disc %,After Disc,Item Cost,Order Type
4,742,CA-2019-112326,2019-01-05 00:00:00,2019-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,7.080,0.8,0.7080,0.2,Order
29,7662,CA-2019-105417,2019-01-08 00:00:00,2019-01-13,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,Acco Four Pocket Poly Ring Binder with Label H...,10.430,7,0.8,-18.2525,73.010,0.8,2.0860,0.2,Order
167,8981,CA-2019-108182,2019-02-07 00:00:00,2019-02-11,Second Class,DL-13315,Delfina Latchford,Consumer,United States,Romeoville,...,"Avery Flip-Chart Easel Binder, Black",8.952,2,0.8,-14.7708,17.904,0.8,1.7904,0.2,Order
186,1333,CA-2019-122567,2019-02-17 00:00:00,2019-02-22,Standard Class,MN-17935,Michael Nguyen,Consumer,United States,Dallas,...,Wilson Jones Easy Flow II Sheet Lifters,1.080,3,0.8,-1.7280,3.240,0.8,0.2160,0.2,Order
187,1334,CA-2019-122567,2019-02-17 00:00:00,2019-02-22,Standard Class,MN-17935,Michael Nguyen,Consumer,United States,Dallas,...,Holmes Cool Mist Humidifier for the Whole Hous...,7.960,2,0.8,-13.9300,15.920,0.8,1.5920,0.2,Order
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20947,5311,CA-2022-131254,2022-11-20 00:00:00,2022-11-22,First Class,NC-18415,Nathan Cano,Consumer,United States,Houston,...,Fellowes PB500 Electric Punch Plastic Comb Bin...,1525.188,6,0.8,-2287.7820,9151.128,0.8,305.0376,0.2,Order
21109,8978,CA-2022-156622,2022-11-24 00:00:00,2022-11-27,First Class,JP-15460,Jennifer Patt,Corporate,United States,Dallas,...,Aluminum Screw Posts,6.104,2,0.8,-9.1560,12.208,0.8,1.2208,0.2,Order
21157,9217,CA-2022-103765,2022-11-25 00:00:00,2022-12-01,Standard Class,JG-15310,Jason Gross,Corporate,United States,Odessa,...,Holmes Replacement Filter for HEPA Air Cleaner...,13.762,1,0.8,-24.7716,13.762,0.8,2.7524,0.2,Order
21227,8960,CA-2022-150266,2022-11-26 00:00:00,2022-12-01,Standard Class,RO-19780,Rose O'Brian,Consumer,United States,Houston,...,Fellowes Command Center 5-outlet power strip,67.840,5,0.8,-179.7760,339.200,0.8,13.5680,0.2,Order
21279,3853,CA-2022-130526,2022-11-27 00:00:00,2022-11-30,First Class,GT-14755,Guy Thornton,Consumer,United States,Rockford,...,GBC Premium Transparent Covers with Diagonal L...,33.568,8,0.8,-53.7088,268.544,0.8,6.7136,0.2,Order

## Date Issue

In [21]:
df["Order Date"] = df["Order Date"].astype('string')

In [22]:
np.count_nonzero(df[(df["Order Date"].str.contains("/"))]["Row ID"].unique())

27

In [24]:
df[(df["Order Date"].str.contains("/"))]["Row ID"]

21394    6475
21395    6475
21396    5968
21397    2878
21398    3236
21399    2880
21400    2879
21401    3744
21402    3742
21403    3743
21404    5968
21405    2878
21406    3236
21407    2880
21408    2879
21409    3744
21410    3742
21411    3743
21412    5968
21413    2878
21414    3236
21415    2880
21416    2879
21417    3744
21418    3742
21419    3743
21420    5968
21421    2878
21422    3236
21423    2880
21424    2879
21425    3744
21426    3742
21427    3743
21428    1183
21429    9863
21430    9862
21431    4914
21432    4913
21433    4912
21434    4911
21435    9865
21436    9864
21437    1184
21438    9866
21439    4910
21440    6980
21441    4165
21442    4166
21443    9861
21444    9859
21445    9860
Name: Row ID, dtype: int64